name: Build NosoWallet

on:
  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "changelog.txt", "releasenotes.txt" ]

  pull_request:
    branches: [ main ]
    
jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.operating-system }}
    
    strategy:
      matrix:
        operating-system: [ ubuntu-20.04, ubuntu-latest, windows-latest]
        lazarus-versions: [ stable]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        clean: true
        set-safe-directory: true

    - name: Install Lazarus
      uses: gcarreno/setup-lazarus@v3.2
      with:
        lazarus-version: ${{ matrix.lazarus-versions }}
        with-cache: false

    - name: Unzip packages
      run: unzip -q Packages/\*.zip -d Packages
    - name: Install packages
      run: |
        lazbuild -qqq Packages/Indy10/indylaz.lpk
        lazbuild -qqq Packages/HashLib/src/Packages/FPC/HashLib4PascalPackage.lpk
        lazbuild -qqq Packages/SimpleBaseLib/src/Packages/FPC/SimpleBaseLib4PascalPackage.lpk
        lazbuild -qqq Packages/dcpcrypt-2.0.4.1/dcpcrypt.lpk
        lazbuild -qqq Packages/CryptoLib4Pascal-master/CryptoLib/src/Packages/FPC/CryptoLib4PascalPackage.lpk
        lazbuild -qqq Packages/lazbarcodes/packages/lazbarcodes_runtimeonly.lpk
        lazbuild -qqq Packages/lazbarcodes/packages/lazbarcodes.lpk
        
    - name: Build the Main App (Windows)
      if: ${{ matrix.operating-system == 'windows-latest' }}
      run: |
        lazbuild -B --bm=Release "Noso.lpi"
        mv Noso.exe nosonode-x86_64-win64.exe

    - name: Build the Main App (Ubuntu)
      if: ${{ matrix.operating-system == 'ubuntu-latest' }}
      run: |
        lazbuild -B --bm=Release "Noso.lpi"
        mv Noso nosonode-x86_64-ubuntu-latest

    - name: Build the Main App (Ubuntu)
      if: ${{ matrix.operating-system == 'ubuntu-20.04' }}
      run: |
        lazbuild -B --bm=Release "Noso.lpi"
        mv Noso nosonode-x86_64-ubuntu-20-04
        
    - name: Upload binary (Windows)
      if: ${{ (matrix.operating-system == 'windows-latest')  &&  (matrix.lazarus-versions == 'stable') }}
      uses: actions/upload-artifact@v2
      with:
        name: nosonode
        path: nosonode-x86_64-win64.exe

    - name: Upload binary (Ubuntu)
      if: ${{ (matrix.operating-system == 'ubuntu-latest')  &&  (matrix.lazarus-versions == 'stable') }}
      uses: actions/upload-artifact@v2
      with:
        name: nosonode
        path: nosonode-x86_64-ubuntu-latest
        
    - name: Upload binary (Ubuntu)
      if: ${{ (matrix.operating-system == 'ubuntu-20.04')  &&  (matrix.lazarus-versions == 'stable') }}
      uses: actions/upload-artifact@v2
      with:
        name: nosonode
        path: nosonode-x86_64-ubuntu-20-04

  package-release:
    if: contains(github.ref, '/tags/')

    name: Package and create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> ${GITHUB_OUTPUT}

    - name: Download the Release binary
      uses: actions/download-artifact@v2

    - name: List files
      run: ls -alF nosonode

    - name: Create release files
      run: |
        cd nosonode
        chmod +x nosonode-x86_64-ubuntu-latest nosoearn-x86_64-ubuntu-20-04
        zip -r nosonode-${{ steps.vars.outputs.tag }}-x86_64-win64.zip nosonode-x86_64-win64.exe
        tar -zcvf nosonode-${{ steps.vars.outputs.tag }}-x86_64-ubuntu-latest.tar.gz nosonode-x86_64-ubuntu-latest
        tar -zcvf nosonode-${{ steps.vars.outputs.tag }}-x86_64-ubuntu-20-04.tar.gz nosonode-x86_64-ubuntu-20-04

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        name: nosonode ${{ steps.vars.outputs.tag }}
        body_path: releasenotes.txt
        files: |
          nosonode/*.tar.gz
          nosonode/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
